---
title: "compmus"
author: "popke"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    storyboard: true
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(readr)
library(ggplot2)
library(reshape2)
library(cluster)
```

Column {data-width=650}
-----------------------------------------------------------------------
### Welcome
This dashboard will be a demonstration of correlation between various musical terms, were we will look for correlations between music in various ways. By using the music metrics of the music corpus of the computational musicology class of 2025 we will try to get a better understanding of music and sound. 

### Data applied on test visualisation


```{r}
aisc2024 <- read_csv("compmus2025.csv")
aisc2024 |>                   # Start with the data
  ggplot(                     # Set up the plot.
    aes(
      x = tempo,
      y = arousal,
      size = instrumentalness,
      colour = danceability
    )
  ) +
  geom_point() +              # Scatter plot.
  geom_rug(linewidth = 0.1) + # Add 'fringes' to show data distribution.
  geom_text(                  # Add text labels from above.
    x = 121,
    y = 4.91,
    label = "Onda Corta - Sud America",
    size = 3,                 # Override size (not loudness here).
    hjust = "left",           # Align left side of label with the point.
    vjust = "center",         # Align vertical centre of label with the point.
    angle = 30                # Rotate the text label
  ) +
  scale_x_continuous(         # Fine-tune the x axis.
    limits = c(50, 200),
    breaks = c(50, 100, 150, 200), # Specify grid lines
    minor_breaks = NULL       # Remove 'minor' grid lines.
  ) +
  scale_y_continuous(         # Fine-tune the y axis in the same way.
    limits = c(1, 9),
    breaks = c(1, 5, 9),
    minor_breaks = NULL
  ) +
  scale_colour_viridis_c() +  # Use the popular viridis colour palette.
  scale_size_continuous(      # Fine-tune the sizes of each point.
    trans = "exp",            # Use an exp transformation to emphasise loud..
    guide = "none"            # Remove the legend for size.
  ) +
  theme_light() +             # Use a simpler theme.
  labs(                       # Make the titles nice.
    x = "Tempo",
    y = "Arousal",
    colour = "Danceability"
  )
ggplotly()
```
### histogram tempo
```{r}

cm2025 <- read_csv("compmus2025.csv")
  ggplot(cm2025, aes(x= tempo)) + geom_histogram()
  ggplotly()
```


### correlation tempo and danceability
```{r}
cm2025 <- read_csv("compmus2025.csv")
ggplot(cm2025, aes(x = tempo, y = danceability)) +
  geom_point(aes(color = engagingness), alpha = 0.7) +
  theme_minimal() +
  labs(title = "Tempo vs. Danceability", x = "Tempo", y = "Danceability") +
  scale_color_gradient(low = "purple", high = "orange")
ggplotly()
```
### Toughts 

So far we can see there is a correlation between tempo and danceablility. 


Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

